# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAH-mpwB7g3MnqYU-ooUBF1t99RP27dZ9addtMVXD";
    path = fetchzip {
      url = "https://www.sqlite.org/2025/sqlite-amalgamation-3490200.zip";
      hash = "sha256-zw9D86WTkqQlZIKcu2z808+4mc11bqct4GLnQsavDRw=";
    };
  }
  {
    name = "sqlite-3.48.0-F2R_ayuQDgATJL_BQ-5jv8zuzgnGwZ8ZDuhecttteNci";
    path = fetchgit {
      url = "https://github.com/vrischmann/zig-sqlite";
      rev = "2051af63d6c34bbbc40bb39945d188acdb132eb9";
      hash = "sha256-aqugNPEsFJApaasPxXDpC20dK//0f5b02zePVUfcXVw=";
    };
  }
  {
    name = "uucode-0.2.0-ZZjBPlK5VADj7fdoq7G8LIHzD5o6FSkcBXXrRWr4jnrA";
    path = fetchgit {
      url = "https://github.com/jacobsandlund/uucode";
      rev = "2826a37a4562284fdacd8fa029d49509cc9bffcd";
      hash = "sha256-R5RXW5tWIaDq5JOF2+oWd5YOYOyns6WH7f687WE+b20=";
    };
  }
  {
    name = "vaxis-0.6.0-BWNV_C75CQAK-GVdeEw41oYi65WqsXybxCW6hlIzozNy";
    path = fetchgit {
      url = "https://github.com/rockorager/libvaxis";
      rev = "762f325d31a92fd2dc83aa1899a412fb1b6f020d";
      hash = "sha256-sZYa4CTsCgWZA/dFNAWQVZpJwfZluVsIeCKqY2KVyMY=";
    };
  }
  {
    name = "zigimg-0.1.0-8_eo2oyaFwBZwJpmqPkCfVXWBrHcqbYwmrp1I6bTD3lI";
    path = fetchgit {
      url = "https://github.com/zigimg/zigimg";
      rev = "d695acd97c02e57bb151e8f659d1280f5cd6ca70";
      hash = "sha256-0IYATQldT6eJxRR2T/2CsIYZuzomqjvmdVyjmsjguyE=";
    };
  }
]
