# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAH-mpwB7g3MnqYU-ooUBF1t99RP27dZ9addtMVXD";
    path = fetchzip {
      url = "https://www.sqlite.org/2025/sqlite-amalgamation-3490200.zip";
      hash = "sha256-zw9D86WTkqQlZIKcu2z808+4mc11bqct4GLnQsavDRw=";
    };
  }
  {
    name = "sqlite-3.48.0-F2R_a8eODgD9X8XjvWlZ1K7C-tDuHae4FuShM2N-yIT2";
    path = fetchgit {
      url = "https://github.com/vrischmann/zig-sqlite";
      rev = "0b75ba276d34de3141ec1697e3ef7c836d7b38e7";
      hash = "sha256-p52EfIeMpbtkgAOGPjtHSt64FmZABjCZijaZglUPEPQ=";
    };
  }
  {
    name = "uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM";
    path = fetchgit {
      url = "https://github.com/jacobsandlund/uucode";
      rev = "5f05f8f83a75caea201f12cc8ea32a2d82ea9732";
      hash = "sha256-sHPh+TQSdUGus/QTbj7KSJJkTuNTrK4VNmQDjS30Lf8=";
    };
  }
  {
    name = "vaxis-0.5.1-BWNV_JJOCQAtdJyLvrYCKbKIhX9q3liQkKMAzujWS4HJ";
    path = fetchgit {
      url = "https://github.com/rockorager/libvaxis.git";
      rev = "41fff922316dcb8776332ec460e73eaf397d5033";
      hash = "sha256-mpW/t9AVObhEs3jt/fGyybsvaAlzZ4GSkCs3KYrQn0g=";
    };
  }
  {
    name = "zigimg-0.1.0-8_eo2vUZFgAAtN1c6dAO5DdqL0d4cEWHtn6iR5ucZJti";
    path = fetchgit {
      url = "https://github.com/zigimg/zigimg";
      rev = "eab2522c023b9259db8b13f2f90d609b7437e5f6";
      hash = "sha256-e42T/ZmRzuzWAhwWkcWScukcOd6rNZ1VK1wk0XGTVKs=";
    };
  }
]
